public with sharing class Question1 {
    public Question1() {


    public static List<Object> listName = new List<Object>();
    (ID, Name), (Account.Contact_) FROM Account

    b) FIND ALL FIELDS WHERE 'ABC' IN ()
    // selected query of SOSL is suitable beacuse it finds each and every record from given objects that match the field ABC 


    c)with sharing to adhere to acess  


        b) A postivie test class is written with the intention it will pass, while a negative test class is written with the intention it will fail.


    }
}